### ISSUE TITLE
Crash when clicking on "Select..." on a Advanced Vending Block

### ISSUE THREAD

**Issue by ghost** [kamildanak/VendingBlock#10]
This is the log file:

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  BetterFoliageLoader (BetterFoliage-MC1.9-2.0.10.jar)
  FldLoadingPlugin (FastLeafDecay-1.9-1.6.jar)
  LoadingPlugin (ChunkAnimator-MC1.9-1.1.jar)
  DLFMLCorePlugin (DynamicLights-1.9.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 04/05/16 17.53
Description: Updating screen events

java.lang.NoSuchMethodError: net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.getObject(Lnet/minecraft/util/ResourceLocation;)Ljava/lang/Object;
    at info.jbcs.minecraft.vending.inventory.ContainerPickBlock.<init>(ContainerPickBlock.java:32)
    at info.jbcs.minecraft.vending.gui.GuiPickBlock.<init>(GuiPickBlock.java:24)
    at info.jbcs.minecraft.vending.gui.GuiAdvancedVendingMachine.func_146284_a(GuiAdvancedVendingMachine.java:40)
    at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:452)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:320)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:540)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:509)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1694)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at info.jbcs.minecraft.vending.inventory.ContainerPickBlock.<init>(ContainerPickBlock.java:32)
    at info.jbcs.minecraft.vending.gui.GuiPickBlock.<init>(GuiPickBlock.java:24)
    at info.jbcs.minecraft.vending.gui.GuiAdvancedVendingMachine.func_146284_a(GuiAdvancedVendingMachine.java:40)
    at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:452)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:320)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:540)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:509)

-- Affected screen --
Details:
    Screen name: info.jbcs.minecraft.vending.gui.GuiAdvancedVendingMachine

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['hiru'/147, l='MpServer', x=-99,85, y=64,00, z=-4,22]]
    Chunk stats: MultiplayerChunkCache: 289, 289
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-56,64,-52), Chunk: (at 8,4,12 in -4,-4; contains blocks -64,0,-64 to -49,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
    Level time: 17399 game time, 5786 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 49 total; [EntitySkeleton['Skeleton'/2690, l='MpServer', x=-158,50, y=29,00, z=-61,50], EntityCreeper['Creeper'/259, l='MpServer', x=-63,50, y=47,00, z=46,50], EntitySkeleton['Skeleton'/3075, l='MpServer', x=-73,50, y=48,00, z=55,50], EntityZombie['Zombie'/2954, l='MpServer', x=-61,50, y=34,00, z=10,50], EntityCreeper['Creeper'/3213, l='MpServer', x=-178,50, y=30,00, z=-17,50], EntitySkeleton['Skeleton'/2958, l='MpServer', x=-153,50, y=30,00, z=-28,50], EntityCreeper['Creeper'/3214, l='MpServer', x=-176,54, y=31,00, z=-13,83], EntitySquid['Squid'/2962, l='MpServer', x=-39,47, y=61,69, z=-27,46], EntityCreeper['Creeper'/19, l='MpServer', x=-178,50, y=29,00, z=-13,50], EntitySquid['Squid'/2963, l='MpServer', x=-38,63, y=60,16, z=-29,48], EntitySquid['Squid'/2964, l='MpServer', x=-38,24, y=57,88, z=-24,80], EntityZombie['Zombie'/279, l='MpServer', x=-161,50, y=24,00, z=-66,50], EntityCreeper['Creeper'/3096, l='MpServer', x=-103,50, y=31,00, z=-18,50], EntitySkeleton['Skeleton'/3097, l='MpServer', x=-58,50, y=39,00, z=39,50], EntitySkeleton['Skeleton'/284, l='MpServer', x=-33,50, y=81,00, z=-70,50], EntitySkeleton['Skeleton'/30, l='MpServer', x=-166,50, y=15,00, z=-41,50], EntityZombie['Zombie'/2977, l='MpServer', x=-143,11, y=26,00, z=-50,11], EntityZombie['Zombie'/2979, l='MpServer', x=-142,07, y=26,00, z=-49,15], EntityPlayerSP['hiru'/147, l='MpServer', x=-99,85, y=64,00, z=-4,22], EntitySkeleton['Skeleton'/2729, l='MpServer', x=-148,50, y=38,00, z=-24,50], EntitySpider['Spider'/48, l='MpServer', x=-132,50, y=26,00, z=-32,50], EntitySkeleton['Skeleton'/58, l='MpServer', x=-122,23, y=17,00, z=3,53], EntityMinecartChest['container.minecart'/60, l='MpServer', x=-112,50, y=24,06, z=47,50], EntitySquid['Squid'/62, l='MpServer', x=-124,60, y=57,00, z=44,48], EntityCreeper['Creeper'/196, l='MpServer', x=-55,50, y=34,00, z=19,50], EntitySquid['Squid'/71, l='MpServer', x=-103,25, y=61,20, z=20,44], EntityCreeper['Creeper'/3019, l='MpServer', x=-148,50, y=24,00, z=-43,50], EntityCreeper['Creeper'/3020, l='MpServer', x=-146,50, y=24,00, z=-43,50], EntityBat['Bat'/2381, l='MpServer', x=-158,29, y=39,67, z=1,39], EntityCreeper['Creeper'/3021, l='MpServer', x=-142,50, y=24,00, z=-40,50], EntityBat['Bat'/2384, l='MpServer', x=-121,75, y=13,29, z=10,33], EntitySpider['Spider'/3152, l='MpServer', x=-178,50, y=30,00, z=-17,50], EntityBat['Bat'/81, l='MpServer', x=-83,49, y=58,10, z=-42,04], EntityBat['Bat'/83, l='MpServer', x=-82,41, y=58,04, z=-36,64], EntityItem['item.item.dyePowder.black'/85, l='MpServer', x=-86,20, y=23,00, z=1,62], EntitySquid['Squid'/86, l='MpServer', x=-82,63, y=54,97, z=-2,13], EntityMinecartChest['container.minecart'/87, l='MpServer', x=-90,50, y=30,06, z=74,50], EntityBat['Bat'/89, l='MpServer', x=-55,59, y=30,12, z=23,94], EntityBat['Bat'/90, l='MpServer', x=-51,64, y=32,73, z=30,79], EntitySpider['Spider'/91, l='MpServer', x=-68,50, y=34,00, z=4,50], EntityZombie['Zombie'/92, l='MpServer', x=-69,50, y=45,00, z=14,50], EntityBat['Bat'/3164, l='MpServer', x=-109,59, y=60,17, z=-36,02], EntitySkeleton['Skeleton'/2141, l='MpServer', x=-41,50, y=48,00, z=51,50], EntityBat['Bat'/3167, l='MpServer', x=-108,46, y=60,09, z=-39,07], EntityBat['Bat'/3172, l='MpServer', x=-153,33, y=41,00, z=-26,43], EntityBat['Bat'/3173, l='MpServer', x=-151,25, y=39,10, z=-21,41], EntityBat['Bat'/102, l='MpServer', x=-46,89, y=47,52, z=40,77], EntityCreeper['Creeper'/3057, l='MpServer', x=-65,50, y=33,00, z=8,50], EntityZombie['Zombie'/3066, l='MpServer', x=-91,76, y=23,00, z=-13,52]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:478)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2647)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:387)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.9
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 482244336 bytes (459 MB) / 884539392 bytes (843 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP 9.23 Powered by Forge 12.16.1.1887 Optifine OptiFine_1.9_HD_U_B2 33 mods loaded, 33 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.1.1887.jar) 
    UCHIJAAAA   Forge{12.16.1.1887} [Minecraft Forge] (forge-1.9-12.16.1.1887.jar) 
    UCHIJAAAA   AutoSapling{1.3} [AutoSapling] (AutoSapling-1.3.1 MC1.9.jar) 
    UCHIJAAAA   BetterFoliage{2.0.10} [Better Foliage] (BetterFoliage-MC1.9-2.0.10.jar) 
    UCHIJAAAA   BiomesOPlenty{4.0.1.2006} [Biomes O' Plenty] (BiomesOPlenty-1.9-4.0.1.2006-universal.jar) 
    UCHIJAAAA   ChunkAnimator{1.1} [Chunk Animator] (ChunkAnimator-MC1.9-1.1.jar) 
    UCHIJAAAA   DynamicLights{1.4.1} [Dynamic Lights] (DynamicLights-1.9.jar) 
    UCHIJAAAA   DynamicLights_onFire{1.0.7} [Dynamic Lights Burning Entity Module] (DynamicLights-1.9.jar) 
    UCHIJAAAA   DynamicLights_creepers{1.0.6} [Dynamic Lights Creeper Module] (DynamicLights-1.9.jar) 
    UCHIJAAAA   DynamicLights_dropItems{1.1.0} [Dynamic Lights EntityItem Module] (DynamicLights-1.9.jar) 
    UCHIJAAAA   DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.9.jar) 
    UCHIJAAAA   DynamicLights_mobEquipment{1.1.0} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.9.jar) 
    UCHIJAAAA   DynamicLights_flameArrows{1.0.1} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.9.jar) 
    UCHIJAAAA   DynamicLights_floodLights{1.0.3} [Dynamic Lights Flood Light] (DynamicLights-1.9.jar) 
    UCHIJAAAA   DynamicLights_otherPlayers{1.0.9} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.9.jar) 
    UCHIJAAAA   DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module] (DynamicLights-1.9.jar) 
    UCHIJAAAA   fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.9-1.6.jar) 
    UCHIJAAAA   gravestone{1.2.4} [Gravestone] (Gravestone Mod 1.2.4 .jar) 
    UCHIJAAAA   grnscrn{1.5} [GreenScreen] (greenscreen-mc1.9-1.5.jar) 
    UCHIJAAAA   Harvest{1.9-1.0.1-3} [Harvest] (Harvest-1.9-1.0.1-3.jar) 
    UCHIJAAAA   JEI{3.3.3.197} [Just Enough Items] (jei_1.9-3.3.3.197.jar) 
    UCHIJAAAA   simplehp{1.2.1} [Simple HP] (SimpleHP-1.9-1.2.1.jar) 
    UCHIJAAAA   soundfilters{0.9_for_1.9} [Sound Filters] (SoundFilters-0.9_for_1.9.jar) 
    UCHIJAAAA   stepup{v.2.0.0-mc1.9.0} [StepUp] (StepUp-v.2.0.0-mc1.9.0.jar) 
    UCHIJAAAA   watchfulchevsky{b4} [Trust Is Nice, But...] (TINB_1.9_b4.jar) 
    UCHIJAAAA   AS_UpdateCheck{1.1.7} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.9.jar) 
    UCHIJAAAA   VeinMiner{0.31.5_build.forgePost18010} [Vein Miner] (VeinMiner-1.9_0.31.5.forgePost18010.jar) 
    UCHIJAAAA   VeinMinerModSupport{0.31.5_build.forgePost18010} [Mod Support] (VeinMiner-1.9_0.31.5.forgePost18010.jar) 
    UCHIJAAAA   vending{1.3.1} [vending] (vending-1.9-1.3.4.jar) 
    UCHIJAAAA   Waila{1.7.0} [Waila] (Waila-1.7.0-B2_1.9.jar) 
    UCHIJAAAA   WailaHarvestability{1.1.7} [Waila Harvestability] (WailaHarvestability-mc1.9-1.1.7.jar) 
    UCHIJAAAA   YALSM{2.1.6} [Yet Another Leather Smelting Mod] (yalsm-2.1.6-mc1.9.jar) 
    Loaded coremods (and transformers): 
BetterFoliageLoader (BetterFoliage-MC1.9-2.0.10.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
FldLoadingPlugin (FastLeafDecay-1.9-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
LoadingPlugin (ChunkAnimator-MC1.9-1.1.jar)
  lumien.chunkanimator.asm.ClassTransformer
DLFMLCorePlugin (DynamicLights-1.9.jar)
  atomicstryker.dynamiclights.common.DLTransformer
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 364.72' Renderer: 'GeForce GTX 980 Ti/PCIe/SSE2'
    Launched Version: 1.9-forge1.9-12.16.1.1887
    LWJGL: 2.9.4
    OpenGL: GeForce GTX 980 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 364.72, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

    Using VBOs: No
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: 
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    CPU: 8x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    OptiFine Version: OptiFine_1.9_HD_U_B2
    Render Distance Chunks: 8
    Mipmaps: 4
    Anisotropic Filtering: 1
    Antialiasing: 0
    Multitexture: false
    Shaders: null
    OpenGlVersion: 4.5.0 NVIDIA 364.72
    OpenGlRenderer: GeForce GTX 980 Ti/PCIe/SSE2
    OpenGlVendor: NVIDIA Corporation
    CpuCount: 8
```

**Comment by jtrent238** [comment]
Seems to be something with:
`ContainerPickBlock` and `GuiPickBlock`

```
at info.jbcs.minecraft.vending.inventory.ContainerPickBlock.<init>(ContainerPickBlock.java:32)
    at info.jbcs.minecraft.vending.gui.GuiPickBlock.<init>(GuiPickBlock.java:24)
    at info.jbcs.minecraft.vending.gui.GuiAdvancedVendingMachine.func_146284_a(GuiAdvancedVendingMachine.java:40)
```

**Comment by ghost** [comment]
So is this a mod problem? Not incompatibility with other mods?

**Comment by jtrent238** [comment]
It it a mod problem, not another mod! :sweat_smile:

**Comment by ghost** [comment]
hope the owner will fix it. this is a really good mod, the best of his kind imo

**Comment by jtrent238** [comment]
Yea! :smile_cat:

**Comment by kamildanak** [comment]
Fixed it at one point, works fine now.
