### ISSUE TITLE
Errors in console when using Vending Blocks

### ISSUE THREAD

**Issue by TheOpalium** [kamildanak/VendingBlock#37]
Hello!

I am getting some strange errors in my console when some of my players use/update their Vending Blocks. It's not crashing or anything, but it does spam the console.
```
[19:31:36] [Server thread/FATAL] [VF]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 47
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_171]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_171]
        at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:293) [SpongeImplHooks.class:1.12.2-2705-7.1.0-BETA-3341]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zji000(MinecraftServer.java:3963) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.IndexOutOfBoundsException: Index: 47
        at org.spongepowered.common.item.inventory.lens.impl.collections.DynamicLensCollectionImpl.checkIndex(DynamicLensCollectionImpl.java:156) ~[DynamicLensCollectionImpl.class:1.12.2-2705-7.1.0-BETA-3341]
        at org.spongepowered.common.item.inventory.lens.impl.collections.DynamicLensCollectionImpl.getLens(DynamicLensCollectionImpl.java:94) ~[DynamicLensCollectionImpl.class:1.12.2-2705-7.1.0-BETA-3341]
        at org.spongepowered.common.item.inventory.lens.impl.collections.DynamicLensCollectionImpl.get(DynamicLensCollectionImpl.java:89) ~[DynamicLensCollectionImpl.class:1.12.2-2705-7.1.0-BETA-3341]
        at org.spongepowered.common.item.inventory.lens.impl.collections.SlotCollection.getSlot(SlotCollection.java:135) ~[SlotCollection.class:1.12.2-2705-7.1.0-BETA-3341]
        at org.spongepowered.common.item.inventory.lens.impl.comp.OrderedInventoryLensImpl.init(OrderedInventoryLensImpl.java:94) ~[OrderedInventoryLensImpl.class:1.12.2-2705-7.1.0-BETA-3341]
        at org.spongepowered.common.item.inventory.lens.impl.comp.OrderedInventoryLensImpl.<init>(OrderedInventoryLensImpl.java:58) ~[OrderedInventoryLensImpl.class:1.12.2-2705-7.1.0-BETA-3341]
        at org.spongepowered.common.item.inventory.lens.impl.comp.OrderedInventoryLensImpl.<init>(OrderedInventoryLensImpl.java:51) ~[OrderedInventoryLensImpl.class:1.12.2-2705-7.1.0-BETA-3341]
        at org.spongepowered.common.item.inventory.lens.impl.DelegatingLens.init(DelegatingLens.java:51) ~[DelegatingLens.class:1.12.2-2705-7.1.0-BETA-3341]
        at org.spongepowered.common.item.inventory.lens.impl.DelegatingLens.<init>(DelegatingLens.java:46) ~[DelegatingLens.class:1.12.2-2705-7.1.0-BETA-3341]
        at org.spongepowered.common.item.inventory.util.ContainerUtil.generateAdapterLens(ContainerUtil.java:343) ~[ContainerUtil.class:1.12.2-2705-7.1.0-BETA-3341]
        at org.spongepowered.common.item.inventory.util.ContainerUtil.generateLens(ContainerUtil.java:249) ~[ContainerUtil.class:1.12.2-2705-7.1.0-BETA-3341]
        at org.spongepowered.common.item.inventory.util.ContainerUtil.getLens(ContainerUtil.java:219) ~[ContainerUtil.class:1.12.2-2705-7.1.0-BETA-3341]
        at net.minecraft.inventory.Container.spongeInit(Container.java:1022) ~[afr.class:?]
        at net.minecraft.inventory.Container.detectAndSendChanges(Container.java:1085) ~[afr.class:?]
        at net.minecraft.inventory.Container.detectAndSendChanges(Container.java:1074) ~[afr.class:?]
        at net.minecraft.inventory.Container.addListener(Container.java:1061) ~[afr.class:?]
        at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:101) ~[FMLNetworkHandler.class:?]
        at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550) ~[aed.class:?]
        at com.kamildanak.minecraft.foamflower.gui.GuiHandler.open(GuiHandler.java:54) ~[GuiHandler.class:?]
        at info.jbcs.minecraft.vending.block.BlockVendingMachine.onBlockActivated(BlockVendingMachine.java:96) ~[BlockVendingMachine.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:1275) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.redirect$onProcessRightClickBlock$zim000(NetHandlerPlayServer.java:2410) ~[pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:739) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:55) ~[ma.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:11) ~[ma.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:92) ~[PacketUtil.class:1.12.2-2705-7.1.0-BETA-3341]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zld000(SourceFile:539) ~[hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
        at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
        ... 7 more

```

Minecraft: 1.12.2, Forge: 14.23.4.2735, SpongeForge: 1.12.2-2705-7.1.0-BETA-3341, Vending Block 1.12.2-3.0.1.1

Any ideas how to solve this?

**Comment by PixeLInc** [comment]
Honestly, after a quick look at this stacktrace, it looks like this may be an issue revolving around the GUI lib that this mod uses, foamflower.
There's a class it references, GuiHandler that handles all the indexing and such where it seems to be erroring out on. As shown here:
``at com.kamildanak.minecraft.foamflower.gui.GuiHandler.open(GuiHandler.java:54) ~[GuiHandler.class:?]
``
([Code Linko](https://github.com/kamildanak/Foamflower/blob/master/src/main/java/com/kamildanak/minecraft/foamflower/gui/GuiHandler.java#L54))

and, a link to the repo for the gui lib: https://github.com/kamildanak/Foamflower

**Comment by kamildanak** [comment]
The issue is not related to the GuiHandler.
VendingBlock has Inventory with 14 slots:
- 9 inventory slots
- 1 accept slot
- 4 vend slots

When VendingBlock is not Multiple only 1 from 4 vending slots is display on GUI.
Sponge assumes that there are as many slots in inventory as displayed on GUI and causes IndexOutOfBoundsException.

14 machine slots + 4*9 player slots - 3 hidden slots = 47
Sponge searches all 0 to 46 slots and than is unable to find 47'th slot.
